config/routes.rb
Rails.application.routes.draw do
  resources :searches

  root 'static_pages#home'
  get 'index' => 'books#index'
  get 'new' => 'books#new'
  get 'edit' => 'books#edit'
  get 'browse_index' => 'books#browse_index'
  get 'browse_genre' => 'books#browse_genre'
  get 'browse_tags' => 'books#browse_tags'
  get 'browse_reviews' => 'reviews#browse_reviews'
  get 'browse_ratings' => 'books#browse_ratings'
  get 'browse_selected_genre' => 'books#browse_selected_genre'
  get 'new_review' => 'reviews#new'
  get 'tags/:tag', to: 'books#books_index', as: :tag
  Rails.application.routes.draw do
  resources :searches

  post '/rate' => 'rater#create', :as => 'rate'
  	resources :books do
  		resources :reviews
  		get :tag
  	end
  end
  
  

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :reviews
	has_many :ratings
	mount_uploader :cover, CoverUploader
	#attr_accessor :genre
	validates :title, presence: true, length: {maximum: 500}, uniqueness: true
	validates :author, presence: true, length: {maximum: 200}
	validates :synopsis, presence: true, length: {maximum: 2000}, uniqueness: true
	validates :genre, presence: true, length: {maximum: 100}
	before_save :title_titleize, :author_titleize, :genre_titleize, :synopsis_capitalize
	acts_as_taggable
	# has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
	#attr_accessor :image
	#mount_uploader :image, ImageUploader
	
	# capitalizes the title
	def title_titleize
		self.title = title.downcase.titleize
	end 
	
	# capitalizes the author
	def author_titleize
		self.author = author.titleize
	end
	
	def genre_titleize
		self.genre = genre.downcase.titleize
	end
	
	def synopsis_capitalize
		self.synopsis = synopsis.capitalize
		self.synopsis = synopsis.gsub(/[a-z][^.?!]*/) { |match| match[0].upcase + match[1..-1].rstrip }
	end
	
	def feed
		Review.where("book_id = ?", id)
	end
	
	def self.search_index(search)
  		if search
   		 where('title LIKE ? or author LIKE ?', "%#{search}%", "%#{search}%")
  		else
   		 all
  		end
	end
	
	def self.search_genre(search)
	if search
   		 where('genre LIKE ?', "%#{search}%")
  		else
   		 all
  		end
	end
	
	def self.search_tags(search)
	if search
   		 where('name LIKE ?', "%#{search}%")
  		else
   		 all
  		end
	end
	
	def self.search_ratings(search)
		if search
			where('rating LIKE ?', "%#{search}%")
		else 
			all
		end	
	end
	




	

end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :review
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :book
	validates :content, presence: true
	validates :rating, presence: true
	has_many :ratings
	before_save :content_capitalize
	
	def content_capitalize
		self.content = content.capitalize
		self.content = content.gsub(/[a-z][^.?!]*/) { |match| match[0].upcase + match[1..-1].rstrip }
	end
	
	
	
	def self.search_reviews(search)
	if search
   		 where('content LIKE ?', "%#{search}%")
  		else
   		 all
  		end
	end
	
end

app/models/search.rb
class Search < ActiveRecord::Base

	def self.search(search)
  		if search
   		 where('title LIKE ? or author LIKE ?', "%#{search}%", "%#{search}%")
  		else
   		 all
  		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #require 'carrierwave'
#require 'carrierwave/orm/activerecord'


end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def index
  	@books = Book.all.order('created_at DESC').paginate(:per_page => 12, :page => params[:page])
  end 
  
  def browse_index
  	@books = Book.all.search_index(params[:search]).paginate(:per_page => 12, :page => params[:page])
  end
  
  def books_index
  	if params[:tag].present?
  		@books = Book.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 12)
  	else
  		@books = Book.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
  	end
  end
  
	def browse_genre
		@books = Book.all.search_genre(params[:search]).order('created_at DESC').paginate(:per_page => 12, :page => params[:page])
	end
	
	
	def browse_ratings
		@books = Book.all.joins(:reviews).search_ratings(params[:search]).order('created_at DESC').paginate(:per_page => 12, :page => params[:page])
	end
	
	def browse_tags 
		@books = Book.all.joins(:tags).search_tags(params[:search]).order('created_at DESC').paginate(:per_page => 12, :page => params[:page])
	end


  
  def show
  	@book = Book.find(params[:id])
  	@reviews = @book.reviews.paginate(page: params[:page])
  end 
  
  def new
  	@book = Book.new
  end
  
  def create
  	@book = Book.new(book_params) 
  	# @book.book_id = session[:id]
  	if @book.save
  		flash[:success] = "Book created!"
  		redirect_to index_url
  	else
  		flash[:danger] = "A book field was not entered correctly."
  		render 'new' 
  	end 
  end 
  
  def update
  	@book = Book.find(params[:id]) # also, don't used find_by on update, will not save correctly. 
  	if @book.update_attributes(book_params)
  		flash[:success] = "Book updated!"
  		redirect_to @book
  	else
  		flash[:danger] = "A book field was not entered correctly."
  		render 'edit'
  	end
  end
  
  def edit
  	@book = Book.find(params[:id]) # don't use find_by on an edit action, will render the wrong information.
  end
  
  def destroy
  	@book = Book.find(params[:id]).destroy
  	flash[:info] = "Book deleted." 
  	redirect_to index_url
  end
  
  def book_params 
  	params.require(:book).permit(:title, :author, :genre, :synopsis, :cover, :tag_list)
  end 
  
  def find_book
  	@book = Book.find_by(params[:id])
  end
  
  def current_book
  	@current_book ||= Book.find_by(id: session[:book_id])
  end
  
  def create_id(book)
	@book = Book.find(params[:id])
	@book.id = :book_id
  end
  
  
  
  
  


  
 
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book
	before_action :find_review, only: [:edit, :update, :destroy]
  
  def new
  	@review = Review.new
  end 
   
  
  def create
  	@review = Review.new(review_params)
  	@review.book_id = @book.id
  	if @review.save
  		flash[:success] = "Review created!"
  		redirect_to @book
  	else 
  		@review.save
  		flash[:info] = "Review not created"
  		redirect_to @book
  	end
  end 
  
  def index
  	@reviews = Review.all.paginate(:per_page => 12, :page => params[:page])
end


	def browse_reviews
		@reviews = Review.all.search_reviews(params[:search]).paginate(:per_page => 12, :page => params[:page])
		@books = Book.all
	end
  
  def edit
  	@review = Review.find(params[:id])
  end
  
  def update 
  	@review = Review.find(params[:id])
  	if @review.update(review_params)
  		flash[:success] = "review updated!"
  		redirect_to @book
  	else 
  		flash[:danger] = "A review field was not entered correctly."
  		render 'edit'
  	end
  end
  
  def destroy
  	@review = Review.find(params[:id]).destroy
  	flash[:info] = "Review deleted."
  	redirect_to @book
  end 
  
  def review_params
  	params.require(:review).permit(:content, :rating)
  end
  
  def find_book
  	@book = Book.find(params[:book_id])
  end
  
  def find_review 
  	@review = Review.find(params[:id])
  end
  
 
 
 
 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def full_title(page_title = ' ')
		base_title = "Goodreads book reviews"
		if page_title.empty?
			base_title
		else 
			"#{page_title} | #{base_title}"
		end
	end
	

end

app/helpers/books_helper.rb
module BooksHelper

	def create_id(book)
		session[:book_id] = book.id
	end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/_book.html.erb
<li>
	<div>
		<%= image_tag book.cover_url(:thumb).to_s, class: "index-book-cover" %>
	</div>
	<div class = "index-book-info">
		<%= link_to book.title, book %>
		<p>by <%= book.author %> </p>
	<div>
</li>

app/views/books/_books.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

app/views/books/_form.html.erb
<div class = "row"> 
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for @book, :html => {:multipart => true} do |f| %>
			<%= f.label :title %> 
			<%= f.text_field :title, class: "form-control" %> 
			
			<%= f.label :author %> 
			<%= f.text_field :author, class: "form-control" %>
			
			<%= f.label :genre %>
			<%= f.text_field :genre, class: "form-control" %>
			
			<%= f.label :synopsis %> 
			<%= f.text_area :synopsis, class: "form-control", :style => "height: 200px; vertical-align: text-top;"%>
			
			<%= f.label :cover %>
			<%= f.file_field :cover %>
			
			<div class="form-group">
				<%= f.label :tags, "Tags (seperated by commas)" %>
				<%= f.text_field :tag_list, :value => @book.tag_list.join(", "), class: "form-control" %> 
			</div>
			
			
			<p class = "line-height"></p>
			
			<% if current_page?(controller: 'books', action: 'new') %>
				<%= f.submit  "Create a book", class: "btn btn-primary", data: {disable_with: "Creating..."} %> 
			<% else current_page?(controller: 'books', action: 'edit') %>
				<%= f.submit  "Save changes", class: "btn btn-primary", data: {disable_with: "Saving..."} %> 
			<% end %>
		<% end %>
	</div>
</div>

app/views/books/_genre.html.erb
<% @books.select(:genre).distinct.each do |book| %>
	<%= link_to book.genre, browse_selected_genre_path %>
<% end %>

app/views/books/_search_form.html.erb
<% form_for @search do |f| %>
  <p>
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </p>
  <p>
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name, :include_blank => true %>
  </p>
  <p>
    Price Range<br />
    <%= f.text_field :minimum_price, :size => 7 %> -
    <%= f.text_field :maximum_price, :size => 7 %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/books/browse_genre.html.erb
<%= provide(:title, "Browse Genre") %>

<%= link_to "Back", browse_index_path, class: "back" %>

<h1>Browse by Genre</h1>

<div>
	<%= form_tag @book, :method => 'get', :id => "products_search" do %>
  		<p>	
    		<%= text_field_tag :search, params[:search] %>
    		<%= submit_tag "Search", :name => nil %>
  		</p>
  		
  		<div id="books"><%= render 'books' %></div>
  		
	<% end %>
</div>


<ul class = "books" > 
	<%= render @books %>
</ul>


<%= will_paginate @books %>

app/views/books/browse_index.html.erb
<%= provide(:title, "Browse") %>

<h1>Browse</h1>

<h3><%= link_to "Genre", browse_genre_path, class: "browse-links" %></h3>
<h3><%= link_to "Rating", browse_ratings_path, class: "browse-links" %></h3>
<h3><%= link_to "Tags", browse_tags_path, class: "browse-links" %></h3>

<div>
	<%= form_tag @book, :method => 'get', :id => "products_search" do %>
  		<p>	
    		<%= text_field_tag :search, params[:search] %>
    		<%= submit_tag "Search", :name => nil %>
  		</p>
  		
  		<div id="books"><%= render 'books' %></div>
  		
	<% end %>
</div>


<ul class = "books" > 
	<%= render @books %>
</ul>

<%= will_paginate @books %>

app/views/books/browse_ratings.html.erb
<%= provide(:title, "Browse Ratings") %>

<%= link_to "Back", browse_index_path, class: "back" %>

<h1>Browse by Ratings</h1>

<%= form_tag @book, :method => 'get' do %>
  		<p>	
    		<%= text_field_tag :search, params[:search] %>
    		<%= submit_tag "Search", :name => nil %>
  		</p>
  		
  		
<% end %>

<ul class = "books" > 
	<%= render @books.uniq %>
</ul>

<%= will_paginate @books.uniq %>

app/views/books/browse_tags.html.erb
<%= provide(:title, "Browse Tags") %>

<%= link_to "Back", browse_index_path, class: "back" %>

<h1>Browse by Tags</h1>

<div>
	<%= form_tag @book, :method => 'get', :id => "products_search" do %>
  		<p>	
    		<%= text_field_tag :search, params[:search] %>
    		<%= submit_tag "Search", :name => nil %>
  		</p>
  		
  		<div id="books"><%= render 'books' %></div>
  		
	<% end %>
</div>



<ul class = "books" > 
	<%= render @books.uniq %>
</ul>

<%= will_paginate @books.uniq %>

app/views/books/edit.html.erb
<%= provide(:title, "Edit") %>

<div class = "edit-choices">
	<li><%= link_to 'Back', @book, class: "edit-back-button" %></li>
</div>
	
<h1>Edit Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<% provide(:title, "Books Index") %> 
<div>
	<h1 class = "books-heading">Books</h1>
	<h3 class = "new-book"><%= link_to "New Book", new_path %></h3>
</div>


<ul class = "books" > 
	<%= render @books %>
</ul>

<%= will_paginate @books %>

app/views/books/index.js.erb
$("#books").html("<%= escape_javascript(render("books")) %>");

app/views/books/new.html.erb
<% provide(:title, 'New Book') %> 

<%= link_to "Back", index_path, class: "back" %>

<h1>New Book</h1>

<%= render 'form' %>



<%#:html => {:multipart => true} <-- add after (@book) if using carrierwave %>

app/views/books/show.html.erb
<%= provide(:title, @book.title) %>
<div class = "center jumbotron" id = "center-width">

<%= link_to "Back", :back, class: "back" %>

<table class = "table-position"> 
	<tr>
		<td>
			<div class = "table-align">
				<div>
					<%= image_tag @book.cover_url(:thumb).to_s, class: "show-book-cover" %>
				</div>
			</div>
		<td>
		<td class = "table-align">
			<div class = "show-book-title">
				<%= @book.title  %>
			</div>
			<div class = "show-book-author"> 
				by <%= @book.author %>
			</div>
			<div>
				<%= @book.synopsis %>
			</div>
			<div> 
				Genre: <%= @book.genre %>
			</div>
			<div>
			<% if @book.tags.any? %>
				<div class = "tag-title">
					Tagged as: 
				</div>
     			<% @book.tags.each do |tag| %>
     			<div>
     				<li class = "tag-list"><%= tag.name %>,</li>
     			</div> 
     			<% end %>
     		<% else %>
     			<div></div>
     		<% end %>
			</div>
		</td>
	</tr>	
</table>
	<div>
		<div>
			<h3 class = "edit-book"><%= link_to "Edit Book", edit_book_path(@book) %></h3>
		</div>
		<div>
			<h3 class = "delete-book"><%= link_to "Delete Book", @book, method: :delete, data: {confirm: "You sure?"} %></h3>
		</div>
	</div>
</div>

<br></br>

<div class = "center jumbotron">
<div>
	<h3 class = "show-add-review" ><%= link_to "Add Review", new_book_review_path(@book) %></h3>
</div>
<div>
	<% @reviews.each do |review| %>
		<div class = "show-show-reviews">
		<%= render review %>
		</div>
	<% end %>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class = "footer">
	<small>	
		<p>@2015 SLCINC</p>
		<p>
			<i>Bilbo Baggins? More like Bilbo Swaggins.</i>
		</p>
	</small>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
			<nav>
				<ul class = "nav navbar-nav navbar-left"> 
					<li><%= link_to "Books", index_path %></li>
				</ul>
				<ul class = "nav navbar-nav navbar-right" >
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Browse", browse_index_path %></li>
				</ul>
			</nav>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]-->
  	<script src = "//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  	</script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Goodreads book reviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class = "container" >
		<% flash.each do |message_type, message| %>
			<div class = "alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/reviews/_rating.html.erb
<div class = "review-date">
		<%= review.created_at.strftime("%d/%m/%Y")%>
	</div>
	<div>
		Rated <%= review.rating %> stars
	</div>
	<div>
		<%= review.content %>
	</div>

app/views/reviews/_review.html.erb
<div class = "review-div">
	<div class = "review-date">
		Added <%= review.created_at.strftime("%d/%m/%Y")%>
	</div>
	<div>
		Rated <%= review.rating %> stars
	</div>
	<div>
		<%= review.content %>
	</div>
	<div class = "review-edit-delete" >
		<%= link_to "Edit", edit_book_review_path(review.book, review) %>
		<%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: { confirm: "Are you sure?"} %>
	</div>
</div>

app/views/reviews/_review_form.html.erb
<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for([@book, @book.reviews.build]) do |f| %>
			
			<%= f.label :rating %>
			<%= f.select :rating, ((0..5).map {|i| [i,i] }), class: "form-control" %>
			
			<p class = "line-height"></p>
			
			
			<%= f.label :content %> 
			<%= f.text_area :content, class: "form-control", :style => "height: 200px; vertical-align: text-top;" %> 
			
			<p class = "line-height"></p>
			
			<%= f.submit  "Create review", class: "btn btn-primary", data: {disable_with: "Creating..."} %> 
		
		<% end %>
	</div>
</div>

app/views/reviews/_reviews.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @reviews %>

app/views/reviews/browse_reviews.html.erb
<%= provide(:title, "Browse") %>

<h1>Browse by Reviews</h1>

<div>
	<%= form_tag @rating, :method => 'get', :id => "reviews_search" do %>
  		<p>	
    		<%= text_field_tag :search, params[:search] %>
    		<%= submit_tag "Search", :name => nil %>
  		</p>
  		
  		<div id="reviews"><%= render 'reviews' %></div>
  		
	<% end %>
</div>


<ul class = "reviews" > 
	<%= render @reviews %>
</ul>

<%= will_paginate @reviews %>

app/views/reviews/browse_reviews.js.erb
$("#reviews").html("<%= escape_javascript(render("reviews")) %>");

app/views/reviews/edit.html.erb
<%= provide(:title, "Edit Review") %>

<%= link_to "Back", @book %>

<h1>Edit Review</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for([@book, @review]) do |f| %>

			<%= f.label :content %>
			<%= f.text_field :content, class: "form-control" %>
	
			<p class = "line-height"></p>
	
			<%= f.submit "Update review", class: "btn btn-primary", data: {disable_with: "Updating..."} %>

		<% end %>
	</div>
</div>

app/views/reviews/new.html.erb
<%= provide(:title, "New Review") %>

<%= link_to "Back", @book %>

<h1>Create a Review</h1>

<%= render 'review_form' %>

app/views/reviews/review:text.html.erb
<h1>Reviews#review:text</h1>
<p>Find me in app/views/reviews/review:text.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %> 
<div class = "center jumbotron">
	<h1>Goodreads App<h1>
	<h3>For all your lovely book reviews<h3> 
	<div>
		<%= image_tag ("lotr.png"), :size => '160x240' %>
		<%= image_tag ("hp"), :size => '160x240' %>
		<%= image_tag ("nlmg"), :size => '160x240' %>
		<%= image_tag ("kl"), :size => '160x240' %>
	</div>
	<br></br>
	<div>
		<%= image_tag ("itw"), :size => '160x240' %>
		<%= image_tag ("be"), :size => '160x240' %>
		<%= image_tag ("f"), :size => '160x240' %>
		<%= image_tag ("trata"), :size => '160x240' %>
	</div>
</div>